language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_script:
    - composer self-update
    - composer install --dev

script:
    - make test-coverage

after_script:
    - CODECLIMATE_REPO_TOKEN=f9f837f0767ec0ad694189f05b13e85c065c0b184c958993deab82f0b71f6046 ./vendor/bin/test-reporter
